'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Merriweather } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/Header";
import { AuthContextProvider } from '../context/AuthContext'
import { UserContextProvider } from "@/context/UserContext";
import { usePathname } from "next/navigation";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap'
});

const merriweather = Merriweather({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-merriweather',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  let showWriteButton = true;

  if (pathname.startsWith('/form')) showWriteButton = false;
  if (pathname.startsWith('/f/')) showWriteButton = false;
  if (pathname.startsWith('/detail')) showWriteButton = false;
  if (pathname.startsWith('/d/')) showWriteButton = false;

  return (
    <html lang="en">

      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} antialiased`}>
        <AuthContextProvider>
          <UserContextProvider>
            <HeaderComponent showWriteButton={showWriteButton} />
            <div>
              {children}
            </div>

          </UserContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
